apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    stage: production
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "disk-1"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    stage: production
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      stage: production
  volumeClaimTemplates:
    - metadata:
        name: mysql-claim
        labels:
          stage: production
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 10Gi
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
        stage: production
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "secret"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-claim
