apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeper-env
  namespace: vodeamail-infrastructure
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: vodeamail-infrastructure
  labels:
    stage: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      stage: production
  template:
    metadata:
      labels:
        app: zookeeper
        stage: production
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: zookeper-env
          ports:
            - containerPort: 2181
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: vodeamail-infrastructure
  labels:
    app: zookeeper
    stage: production
spec:
  type: NodePort
  selector:
    app: zookeeper
    stage: production
  ports:
    - port: 2181
      targetPort: 2181
