apiVersion: v1
kind: Service
metadata:
  name: ms-account
  namespace: vodeamail
  labels:
    stage: production
spec:
  type: ClusterIP
  selector:
    app: ms-account
    stage: production
  ports:
    - port: 3010
      targetPort: 3010
