apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-audience-config
  namespace: vodeamail
data:
  APP_HOST: "0.0.0.0"
  APP_PORT: "3020"
  DB_DATABASE: "vodeamail-audience-service"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-audience
  namespace: vodeamail
  labels:
    stage: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-audience
      stage: production
  template:
    metadata:
      labels:
        app: ms-audience
        stage: production
    spec:
      volumes:
        - name: mysql-account-secret
          secret:
            secretName: vodeacloud-mysql-account
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=vodea-cloud:asia-southeast2:mysql-1=tcp:3306"
            - "-credential_file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: mysql-account-secret
              mountPath: /secrets/
              readOnly: true
        - name: ms-audience
          image: asia.gcr.io/vodea-cloud/vodeamail-audience-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3020
          envFrom:
            - configMapRef:
                name: ms-audience-config
            - secretRef:
                name: vodeacloud-mysql
      restartPolicy: Always
