apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-audience-config
  namespace: vodeamail
data:
  APP_HOST: "0.0.0.0"
  APP_PORT: "3020"
  DB_DATABASE: "vodeamail-audience-service"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-audience
  namespace: vodeamail
  labels:
    stage: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-audience
      stage: production
  template:
    metadata:
      labels:
        app: ms-audience
        stage: production
    spec:
      containers:
        - name: ms-audience
          image: tanyudii/vodeamail-audience-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3020
          envFrom:
            - configMapRef:
                name: ms-audience-config
            - secretRef:
                name: vodea-db-staging
      restartPolicy: Always
