apiVersion: v1
kind: Service
metadata:
  name: ms-audience
  namespace: vodeamail
  labels:
    stage: production
spec:
  type: ClusterIP
  selector:
    app: ms-audience
    stage: production
  ports:
    - port: 3020
      targetPort: 3020

---

apiVersion: v1
kind: Service
metadata:
  name: ms-audience-lb
  namespace: vodeamail
  labels:
    stage: production
spec:
  type: LoadBalancer
  selector:
    app: ms-audience
    stage: production
  ports:
    - port: 3020
      targetPort: 3020
