apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-campaign-config
  namespace: vodeamail
data:
  APP_HOST: "0.0.0.0"
  APP_PORT: "3030"
  DB_DATABASE: "vodeamail-campaign-service"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-campaign
  namespace: vodeamail
  labels:
    stage: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-campaign
      stage: production
  template:
    metadata:
      labels:
        app: ms-campaign
        stage: production
    spec:
      containers:
        - name: ms-campaign
          image: tanyudii/vodeamail-campaign-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3030
          envFrom:
            - configMapRef:
                name: ms-campaign-config
            - secretRef:
                name: vodea-db-staging

      restartPolicy: Always
