apiVersion: v1
kind: Service
metadata:
  name: ms-mailer
  namespace: vodeamail
  labels:
    stage: production
spec:
  type: ClusterIP
  selector:
    app: ms-mailer
    stage: production
  ports:
    - port: 3100
      targetPort: 3100
