apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: vodeamail
data:
  APP_HOST: "0.0.0.0"
  APP_PORT: "3000"
  DB_DATABASE: "vodeamail-api-gateway"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: vodeamail
  labels:
    stage: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      stage: production
  template:
    metadata:
      labels:
        app: gateway
        stage: production
    spec:
      containers:
        - name: gateway
          image: tanyudii/vodeamail-api-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: gateway-config
            - configMapRef:
                name: application-services
            - secretRef:
                name: gateway-jwt
            - secretRef:
                name: vodea-db-staging
      restartPolicy: Always
