apiVersion: v1
kind: ConfigMap
metadata:
  name: public-config
  namespace: vodeamail
data:
  APP_HOST: "0.0.0.0"
  APP_PORT: "3000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: public
  namespace: vodeamail
  labels:
    stage: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: public
      stage: production
  template:
    metadata:
      labels:
        app: public
        stage: production
    spec:
      containers:
        - name: public
          image: asia.gcr.io/vodea-cloud/vodeamail-public
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: public-config
            - configMapRef:
                name: application-services
      restartPolicy: Always
