apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: vodeamail
  labels:
    stage: production
spec:
  type: ClusterIP
  selector:
    app: frontend
    stage: production
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: vodeamail
  labels:
    stage: production
spec:
  type: LoadBalancer
  selector:
    app: frontend
    stage: production
  ports:
    - port: 80
      targetPort: 80
