apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: vodeamail
  labels:
    stage: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      stage: production
  template:
    metadata:
      labels:
        app: frontend
        stage: production
    spec:
      containers:
        - name: frontend
          image: asia.gcr.io/vodea-cloud/vodeamail-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: vodeamail
  labels:
    stage: example
spec:
  type: LoadBalancer
  loadBalancerIP: 34.101.97.155
  selector:
    app: frontend
    stage: production
  ports:
    - port: 80
      targetPort: 80
