version: "3.3"
services:
  nest-first-service:
    image: tanyudii/nest-first-service
    container_name: nest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - APP_PORT=3000
      - APP_MESSAGE=Hello From First
    networks:
      - example
  nest-second-service:
    image: tanyudii/nest-second-service
    container_name: nest-second-service
    restart: unless-stopped
    ports:
      - 3010:3010
    environment:
      - APP_PORT=3010
      - APP_MESSAGE=Hello From Second
    networks:
      - example
networks:
  example:
    driver: bridge
