apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-account-config
  namespace: vodeamail
data:
  APP_HOST: "0.0.0.0"
  APP_PORT: "3010"
  DB_DATABASE: "vodeamail-account-service"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-account
  namespace: vodeamail
  labels:
    stage: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-account
      stage: production
  template:
    metadata:
      labels:
        app: ms-account
        stage: production
    spec:
      containers:
        - name: ms-account
          image: tanyudii/vodeamail-account-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3010
          envFrom:
            - configMapRef:
                name: ms-account-config
            - configMapRef:
                name: application-services
            - secretRef:
                name: vodea-db-staging
      restartPolicy: Always
