apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-mailer-config
  namespace: vodeamail
data:
  APP_HOST: "0.0.0.0"
  APP_PORT: "3100"
  DB_DATABASE: "vodeamail-mailer-service"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-mailer
  namespace: vodeamail
  labels:
    stage: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-mailer
      stage: production
  template:
    metadata:
      labels:
        app: ms-mailer
        stage: production
    spec:
      containers:
        - name: ms-mailer
          image: tanyudii/vodeamail-mailer-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3100
          envFrom:
            - configMapRef:
                name: ms-mailer-config
            - secretRef:
                name: vodea-db-staging
            - secretRef:
                name: mailhog-staging
      restartPolicy: Always
