apiVersion: v1
kind: Secret
metadata:
  name: mailhog-staging
  namespace: vodeamail
data:
  MAIL_HOST: MTY3Ljk5LjczLjE3MA==
  MAIL_PORT: MTAyNQ==
  MAIL_USERNAME: dGVzdHVzZXI=
  MAIL_PASSWORD: dGVzdHBhc3N3b3Jk
