apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vodeacloud
  labels:
    stage: production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: vodeacloud-ip
spec:
  defaultBackend:
    service:
      name: frontend
      port:
        number: 80
