apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vodeacloud
  labels:
    stage: production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: vodeacloud-ip
spec:
  rules:
    - host: www.vodea.cloud
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: vodeamail-frontend
                port:
                  number: 80
