apiVersion: v1
kind: Service
metadata:
  name: nestjs-first
  labels:
    stage: example
spec:
  type: NodePort
  selector:
    app: nestjs-first
    stage: production
  ports:
    - port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nestjs-second
  labels:
    stage: example
spec:
  type: NodePort
  selector:
    app: nestjs-second
    stage: production
  ports:
    - port: 3000
      targetPort: 3000
