apiVersion: v1
kind: Service
metadata:
  name: nestjs-first-lb
spec:
  type: LoadBalancer
  selector:
    app: nestjs-first
    stage: example
  ports:
    - port: 80
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nestjs-second-lb
spec:
  type: LoadBalancer
  selector:
    app: nestjs-second
    stage: example
  ports:
    - port: 80
      targetPort: 3000
